### ISSUE TITLE
Want help with the Weibo dataset

### ISSUE THREAD

**Issue by SuYindu** [kite1988/visual-image-tweets#1]
Dear Dr. Chen,

Sorry to bother you again.

I am Su Yindu, a graduate student of Computer Science and Technology at Zhejiang University of China.
My research is focused on multi-modal learning and I am working on a task about image-text relation.

After applying for a web APP with an access token, I try to get Weibo content via this [API](https://open.weibo.com/wiki/2/statuses/show), but get the 20112 error (i.e., "Permission Denied!").
Is there a way to bypass the authority control and get the text and image (or image URL)?
Or is it OK that you share the raw dataset with me?

Please be assured that the data will be used only for my research purposes and will not be shared with any third-party.

I appreciate your kind consideration and look forward to your reply.

**Comment by kite1988** [comment]
Unfortunately, we cannot share the post content with you due to the policy constraint.  To bypass the authority control, I found Weibo web version is accessible without any login requirement (eg, https://m.weibo.cn/detail/4836757223506718). That is to say, you can crawl the html page and then extract the post content.

I also found one Weibo-crawler (https://github.com/dataabc/weibo-crawler), which is under active development. It seems that it does not require any access token. You can try that, too.

**Comment by SuYindu** [comment]
Thank you for your help!The mobile version and Weibo crawler did work, and I

**Comment by SuYindu** [comment]
Thank you for you advice, it helps a lot!

I wrote a simple crawler based on the mobile version address and Weibo crawler, and it works.

While about half of the Weibos are unavailable, I will try to make use of the rest.

**Comment by kite1988** [comment]
Glad to hear that it works:)
